import 'general_enums.dart';

/// The language code is used internally by all the weather factories when generating the url request to
/// the OpenWeather endpoints
Map<Language, String> languageCode = {
  Language.AFRIKAANS: 'af',
  Language.ALBANIAN: 'al',
  Language.ARABIC: 'ar',
  Language.AZERBAIJANI: 'az',
  Language.BASQUE: 'eu',
  Language.BULGARIAN: 'bg',
  Language.CATALAN: 'ca',
  Language.CHINESE_SIMPLIFIED: 'zh_cn',
  Language.CHINESE_TRADITIONAL: 'zh_tw',
  Language.CROATIAN: 'hr',
  Language.CZECH: 'cz',
  Language.DANISH: 'da',
  Language.DUTCH: 'nl',
  Language.ENGLISH: 'en',
  Language.FARSI: 'fa',
  Language.FINNISH: 'fi',
  Language.FRENCH: 'fr',
  Language.GALICIAN: 'gl',
  Language.GERMAN: 'de',
  Language.GREEK: 'el',
  Language.HEBREW: 'he',
  Language.HINDI: 'hi',
  Language.HUNGARIAN: 'hu',
  Language.INDONESIAN: 'id',
  Language.ITALIAN: 'it',
  Language.JAPANESE: 'ja',
  Language.KOREAN: 'kr',
  Language.LATVIAN: 'la',
  Language.LITHUANIAN: 'lt',
  Language.MACEDONIAN: 'mk',
  Language.NORWEGIAN: 'no',
  Language.PERSIAN: 'fa',
  Language.POLISH: 'pl',
  Language.PORTUGUESE: 'pt',
  Language.PORTUGUESE_BRAZIL: 'pt_br',
  Language.ROMANIAN: 'ro',
  Language.RUSSIAN: 'ru',
  Language.SWEDISH: 'sv',
  Language.SLOVAK: 'sk',
  Language.SLOVENIAN: 'sl',
  Language.SPANISH: 'sp',
  Language.SERBIAN: 'sr',
  Language.THAI: 'th',
  Language.TURKISH: 'tr',
  Language.UKRAINIAN: 'ua',
  Language.VIETNAMESE: 'vi',
  Language.ZULU: 'zu',
};
